### ISSUE TITLE
yii2: bower/vis/dist does not exist

### ISSUE THREAD

**Issue by fabiodirosa** [raoul2000/yii2-workflow-view#1]
After have installed the widget and have used the code,
the bower file cannot be linked

The file or directory to be published does not exist: C:\xampp\htdocs\cis.wkt/vendor\bower/vis/dist

**Comment by raoul2000** [comment]
Hi,
can you check in your vendor dir in which folder is located vis ?
Thanks

**Comment by raoul2000** [comment]
you must update your composer-asset-plugin : 

`composer.phar global require "fxp/composer-asset-plugin:~1.1.1"`

After that bower assets should be installed in **vendor/bower**
